# Generated by Django 4.2 on 2023-07-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_comments_comments_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
