# Generated by Django 4.2 on 2023-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comments_options_remove_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='user_comments', to='posts.comments'),
        ),
    ]
