# Generated by Django 4.2.4 on 2023-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_comments', to='posts.comments'),
        ),
    ]
