# Generated by Django 4.2.4 on 2023-10-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
